export const listItems = [
    {
        dataLevel: "2",
        dataCategory: "4",
        dataRoom: "",
        dataSpace: "2.07",
        listLink: "Service Desk",
    },
    {
        dataLevel: "1",
        dataCategory: "4",
        dataRoom: "Stacks",
        dataSpace: "1.07",
        listLink: "Ground Level Stacks",
    },
    {
        dataLevel: "2",
        dataCategory: "4",
        dataRoom: "Stacks",
        dataSpace: "2.04",
        listLink: "First Floor Stacks",
    },
    {
        dataLevel: "3",
        dataCategory: "4",
        dataRoom: "Stacks",
        dataSpace: "3.01",
        listLink: "Second Floor Stacks",
    },
    {
        dataLevel: "4",
        dataCategory: "4",
        dataRoom: "Stacks",
        dataSpace: "4.01",
        listLink: "Third Floor Stacks",
    },
    {
        dataLevel: "1",
        dataCategory: "4",
        dataRoom: "MFLM",
        dataSpace: "1.20",
        listLink: "Microfilm",
    },
    {
        dataLevel: "2",
        dataCategory: "4",
        dataRoom: "NB",
        dataSpace: "2.15",
        listLink: "New Books",
    },
    {
        dataLevel: "2",
        dataCategory: "4",
        dataRoom: "NB",
        dataSpace: "2.16",
        listLink: "Colby Authors",
    },
    {
        dataLevel: "2",
        dataCategory: "4",
        dataRoom: "134",
        dataSpace: "2.18",
        listLink: "Reference Books",
    },
    {
        dataLevel: "2",
        dataCategory: "4",
        dataRoom: "134",
        dataSpace: "2.19",
        listLink: "Periodicals",
    },
    {
        dataLevel: "1",
        dataCategory: "3",
        dataRoom: "Mule Works",
        dataSpace: "1.09",
        listLink: "Mule Works Lab",
    },
    {
        dataLevel: "1",
        dataCategory: "3",
        dataRoom: "Hall",
        dataSpace: "1.21",
        listLink: "Hall Study Area",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "SC",
        dataSpace: "2.14",
        listLink: "Special Collections",
    },
    {
        dataLevel: "1",
        dataCategory: "3",
        dataRoom: "SCP",
        dataSpace: "1.10",
        listLink: "Special Collections Processing",
    },
    {
        dataLevel: "1",
        dataCategory: "3",
        dataRoom: "020A-D",
        dataSpace: "1.19",
        listLink: "Study Rooms 020A-D",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "134",
        dataSpace: "2.02",
        listLink: "Brewster Reading Room",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "113",
        dataSpace: "2.13",
        listLink: "Chapman Room",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "108",
        dataSpace: "2.03",
        listLink: "Robinson Room",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "119",
        dataSpace: "2.08",
        listLink: "Healy Room",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "115",
        dataSpace: "2.12",
        listLink: "Wormser Room",
    },
    {
        dataLevel: "3",
        dataCategory: "3",
        dataRoom: "Hall",
        dataSpace: "3.02",
        listLink: "Second Floor Study Area",
    },
    {
        dataLevel: "4",
        dataCategory: "3",
        dataRoom: "Hall",
        dataSpace: "4.02",
        listLink: "Third Floor Study Area",
    },
    {
        dataLevel: "3",
        dataCategory: "3",
        dataRoom: "206",
        dataSpace: "3.03",
        listLink: "Farnham Writing Center",
    },
    {
        dataLevel: "2",
        dataCategory: "3",
        dataRoom: "105",
        dataSpace: "2.11",
        listLink: "Fit Lab",
    },
    {
        dataLevel: "1",
        dataCategory: "3",
        dataRoom: "005",
        dataSpace: "1.14",
        listLink: "Room 005",
    },
    {
        dataLevel: "1",
        dataCategory: "2",
        dataRoom: "008",
        dataSpace: "1.11",
        listLink: "Classroom 008",
    },
    {
        dataLevel: "1",
        dataCategory: "2",
        dataRoom: "014",
        dataSpace: "1.08",
        listLink: "Classroom 014",
    },
    {
        dataLevel: "3",
        dataCategory: "2",
        dataRoom: "205",
        dataSpace: "3.04",
        listLink: "Room 205",
    },
    {
        dataLevel: "3",
        dataCategory: "2",
        dataRoom: "208",
        dataSpace: "3.05",
        listLink: "Room 208",
    },
    {
        dataLevel: "4",
        dataCategory: "2",
        dataRoom: "305A",
        dataSpace: "4.04",
        listLink: "Room 305 A",
    },
    {
        dataLevel: "4",
        dataCategory: "2",
        dataRoom: "305B",
        dataSpace: "4.03",
        listLink: "Room 305 B",
    },
    {
        dataLevel: "4",
        dataCategory: "2",
        dataRoom: "306A",
        dataSpace: "4.05",
        listLink: "Room 306 A",
    },
    {
        dataLevel: "4",
        dataCategory: "2",
        dataRoom: "306B",
        dataSpace: "4.06",
        listLink: "Room 306 B",
    },
    {
        dataLevel: "4",
        dataCategory: "2",
        dataRoom: "306C",
        dataSpace: "4.07",
        listLink: "Room 306 C",
    },
    {
        dataLevel: "4",
        dataCategory: "2",
        dataRoom: "319",
        dataSpace: "4.08",
        listLink: "Room 319",
    },
    {
        dataLevel: "1",
        dataCategory: "2",
        dataRoom: "034",
        dataSpace: "1.22",
        listLink: "Seminar Room",
    },
    {
        dataLevel: "2",
        dataCategory: "2",
        dataRoom: "104",
        dataSpace: "2.20",
        listLink: "Davis Classroom",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "007B",
        dataSpace: "1.01",
        listLink: "Darylyne Provost",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "007C",
        dataSpace: "1.02",
        listLink: "Mike McGuire",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "007B",
        dataSpace: "1.04",
        listLink: "Mike Jandreau",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "007A",
        dataSpace: "1.03",
        listLink: "Matt LeVan",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "005B",
        dataSpace: "1.06",
        listLink: "Eileen Richards",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "005A",
        dataSpace: "1.05",
        listLink: "Martin Kelly",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "009",
        dataSpace: "1.12",
        listLink: "Room 009",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "009A",
        dataSpace: "1.13",
        listLink: "Room 009A",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "004A",
        dataSpace: "1.15",
        listLink: "Ana Noriega",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "004B",
        dataSpace: "1.16",
        listLink: "Katie Donahue",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "004",
        dataSpace: "1.17",
        listLink: "Room 004",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "028",
        dataSpace: "1.18",
        listLink: "Bess Stokes",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "035",
        dataSpace: "1.23",
        listLink: "Lauren Yoshizawa",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "039",
        dataSpace: "1.24",
        listLink: "Celeste Cessaro",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "038",
        dataSpace: "1.25",
        listLink: "David Casalaspi",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "037",
        dataSpace: "1.26",
        listLink: "Lyn Brown & Mark Tappan",
    },
    {
        dataLevel: "1",
        dataCategory: "1",
        dataRoom: "036",
        dataSpace: "1.27",
        listLink: "Adam Howard",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "130",
        dataSpace: "2.06",
        listLink: "Rachel Gammon",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "106B",
        dataSpace: "2.01",
        listLink: "Ellen Freeman",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "106",
        dataSpace: "2.05",
        listLink: "Mark Wardecker",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "102",
        dataSpace: "2.09",
        listLink: "Tim Stonsifer",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "101",
        dataSpace: "2.10",
        listLink: "Lareese Hall",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "129",
        dataSpace: "2.17",
        listLink: "April Paul",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "106D",
        dataSpace: "2.21",
        listLink: "Stacey Sheriff",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "106C",
        dataSpace: "2.22",
        listLink: "Carol Hurney",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "106A",
        dataSpace: "2.23",
        listLink: "Jason Parkhill",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "107",
        dataSpace: "2.24",
        listLink: "Karen Gillum",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "107A",
        dataSpace: "2.25",
        listLink: "Bonnie Paige",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "107B",
        dataSpace: "2.26",
        listLink: "Marilyn Pukkila",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "107C",
        dataSpace: "2.27",
        listLink: "Laine Thielstrom",
    },
    {
        dataLevel: "2",
        dataCategory: "1",
        dataRoom: "107D",
        dataSpace: "2.28",
        listLink: "Stephanie Frost",
    },
    {
        dataLevel: "3",
        dataCategory: "1",
        dataRoom: "207A",
        dataSpace: "3.06",
        listLink: "Meghan Hancock",
    },
    {
        dataLevel: "3",
        dataCategory: "1",
        dataRoom: "200",
        dataSpace: "3.09",
        listLink: "Kerrill O'Neil",
    },
    {
        dataLevel: "3",
        dataCategory: "1",
        dataRoom: "201",
        dataSpace: "3.10",
        listLink: "Megan Fossa",
    },
    {
        dataLevel: "3",
        dataCategory: "1",
        dataRoom: "202",
        dataSpace: "3.11",
        listLink: "Paula Harrington",
    },
    {
        dataLevel: "3",
        dataCategory: "1",
        dataRoom: "203A",
        dataSpace: "3.12",
        listLink: "FWC Tutor Office",
    },
    {
        dataLevel: "3",
        dataCategory: "1",
        dataRoom: "203B",
        dataSpace: "3.13",
        listLink: "Carolyn Megan",
    },
]

export const listItems1 = [
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 4,
        "data-room": "Stacks",
        "data-space": 1.07,
        linkText: "Ground Level Stacks",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 4,
        "data-room": "MFLM",
        "data-space": "1.20",
        linkText: "Microfilm",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 3,
        "data-room": "Mule Works",
        "data-space": 1.09,
        linkText: "Mule Works Lab",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 3,
        "data-room": "Hall",
        "data-space": 1.21,
        linkText: "Hall Study Area",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 3,
        "data-room": "SCP",
        "data-space": "1.10",
        linkText: "Special Collections Processing",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 3,
        "data-room": "020A-D",
        "data-space": 1.19,
        linkText: "Study Rooms 020A-D",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 3,
        "data-room": "005",
        "data-space": 1.14,
        linkText: "Room 005",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 2,
        "data-room": "008",
        "data-space": 1.11,
        linkText: "Classroom 008",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 2,
        "data-room": "014",
        "data-space": 1.08,
        linkText: "Classroom 014",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 2,
        "data-room": "034",
        "data-space": 1.22,
        linkText: "Seminar Room",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "007B",
        "data-space": 1.01,
        linkText: "Darylyne Provost",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "007C",
        "data-space": 1.02,
        linkText: "Mike McGuire",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "007B",
        "data-space": 1.04,
        linkText: "Mike Jandreau",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "007A",
        "data-space": 1.03,
        linkText: "Matt LeVan",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "005B",
        "data-space": 1.06,
        linkText: "Eileen Richards",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "005A",
        "data-space": 1.05,
        linkText: "Martin Kelly",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "009",
        "data-space": 1.12,
        linkText: "Room 009",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "009A",
        "data-space": 1.13,
        linkText: "Room 009A",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "004A",
        "data-space": 1.15,
        linkText: "Ana Noriega",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "004B",
        "data-space": 1.16,
        linkText: "Katie Donahue",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "004",
        "data-space": 1.17,
        linkText: "Room 004",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "028",
        "data-space": 1.18,
        linkText: "Bess Stokes",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "035",
        "data-space": 1.23,
        linkText: "Lauren Yoshizawa",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "039",
        "data-space": 1.24,
        linkText: "Celeste Cessaro",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "038",
        "data-space": 1.25,
        linkText: "David Casalaspi",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "037",
        "data-space": 1.26,
        linkText: "Lyn Brown & Mark Tappan",
    },
    {
        className: "list__item",
        "data-level": 1,
        "data-category": 1,
        "data-room": "036",
        "data-space": 1.27,
        linkText: "Adam Howard",
    },
]
