export const FirstFloorPins = [
  {
    id: "1",
    aClass: "pin pin--1-1" as string,
    dataSpace: "1.01" as string,
    arialabel: "Pin for Darylyne Provost" as string,
    svgClassName: "icon icon--logo icon--appleheart" as string,
    xlinkHref: "#icon-appleheart" as string,
    dataCategory: "1" as string,
  },
  {
    aClass: "pin pin--1-2",
    dataSpace: "1.02",
    arialabel: "Pin for Mike McGuire",
    svgClassName: "icon icon--logo icon--bananas",
    xlinkHref: "#icon-bananas",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-3",
    dataSpace: "1.03",
    arialabel: "Pin for Matt LeVan",
    svgClassName: "icon icon--logo icon--origami",
    xlinkHref: "#icon-origami",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-4",
    dataSpace: "1.04",
    arialabel: "Pin for Mike Jandreau",
    svgClassName: "icon icon--logo icon--dress",
    xlinkHref: "#icon-dress",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-5",
    dataSpace: "1.05",
    arialabel: "Pin for Martin Kelly",
    svgClassName: "icon icon--logo icon--tree2",
    xlinkHref: "#icon-tree2",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-6",
    dataSpace: "1.06",
    arialabel: "Pin for Eileen Richards",
    svgClassName: "icon icon--logo icon--avocado",
    xlinkHref: "#icon-avocado",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-7",
    dataSpace: "1.07",
    arialabel: "Pin for Ground Level Stacks",
    svgClassName: "icon icon--logo icon--books",
    xlinkHref: "#icon-books",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--1-8",
    dataSpace: "1.08",
    arialabel: "Pin for Classroom 014",
    svgClassName: "icon icon--logo icon--pear",
    xlinkHref: "#icon-pear",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--1-9",
    dataSpace: "1.09",
    arialabel: "Pin for Mule Works Lab",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--1-10",
    dataSpace: "1.10",
    arialabel: "Pin for Special Collections Processing",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--1-11",
    dataSpace: "1.11",
    arialabel: "Pin for Classroom 008",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--1-12",
    dataSpace: "1.12",
    arialabel: "Pin for Room 009",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-13",
    dataSpace: "1.13",
    arialabel: "Pin for Room 009A",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-14",
    dataSpace: "1.14",
    arialabel: "Pin for Room 005",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--1-15",
    dataSpace: "1.15",
    arialabel: "Pin for Ana Noriega",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-16",
    dataSpace: "1.16",
    arialabel: "Pin for Katie Donahue",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-17",
    dataSpace: "1.17",
    arialabel: "Pin for Room 004",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-18",
    dataSpace: "1.18",
    arialabel: "Pin for Bess Stokes",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-19",
    dataSpace: "1.19",
    arialabel: "Pin for Study Rooms 020A-D",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--1-20",
    dataSpace: "1.20",
    arialabel: "Pin for Microfilm",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--1-21",
    dataSpace: "1.21",
    arialabel: "Pin for Hall Study Area",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--1-22",
    dataSpace: "1.22",
    arialabel: "Pin for Seminar Room",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--1-23",
    dataSpace: "1.23",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-24",
    dataSpace: "1.24",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-25",
    dataSpace: "1.25",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-26",
    dataSpace: "1.26",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--1-27",
    dataSpace: "1.27",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  // Add more entries as needed
];
export const SecondFloorPins = [
  {
    aClass: "pin pin--2-1",
    dataSpace: "2.01",
    arialabel: "Pin for Ellen Freeman",
    svgClassName: "icon icon--logo icon--pepper",
    xlinkHref: "#icon-pepper",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-2",
    dataSpace: "2.02",
    arialabel: "Pin for Brewster Reading Room",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-3",
    dataSpace: "2.03",
    arialabel: "Pin for Robinson Room",
    svgClassName: "icon icon--logo icon--bug",
    xlinkHref: "#icon-bug",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-4",
    dataSpace: "2.04",
    arialabel: "Pin for First Floor Stacks",
    svgClassName: "icon icon--logo icon--books",
    xlinkHref: "#icon-books",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--2-5",
    dataSpace: "2.05",
    arialabel: "Pin for Mark Wardecker",
    svgClassName: "icon icon--logo icon--eggplant",
    xlinkHref: "#icon-eggplant",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-6",
    dataSpace: "2.06",
    arialabel: "Pin for Rachel Gammon",
    svgClassName: "icon icon--logo icon--strawberry",
    xlinkHref: "#icon-strawberry",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-7",
    dataSpace: "2.07",
    arialabel: "Pin for Service Desk",
    svgClassName: "icon icon--logo icon--heart",
    xlinkHref: "#icon-heart",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--2-8",
    dataSpace: "2.08",
    arialabel: "Pin for Healy Room",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-9",
    dataSpace: "2.09",
    arialabel: "Pin for Tim Stonsifer",
    svgClassName: "icon icon--logo icon--tea",
    xlinkHref: "#icon-tea",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-10",
    dataSpace: "2.10",
    arialabel: "Pin for Lareese Hall",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-11",
    dataSpace: "2.11",
    arialabel: "Pin for Fit Lab",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-12",
    dataSpace: "2.12",
    arialabel: "Pin for Wormser Room",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-13",
    dataSpace: "2.13",
    arialabel: "Pin for Chapman Room",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-14",
    dataSpace: "2.14",
    arialabel: "Pin for Special Collections",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--2-15",
    dataSpace: "2.15",
    arialabel: "Pin for New Books",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--2-16",
    dataSpace: "2.16",
    arialabel: "Pin for Colby Authors",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--2-17",
    dataSpace: "2.17",
    arialabel: "Pin for April Paul",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-18",
    dataSpace: "2.18",
    arialabel: "Pin for Reference Books",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--2-19",
    dataSpace: "2.19",
    arialabel: "Pin for Periodicals",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--2-20",
    dataSpace: "2.20",
    arialabel: "Pin for Davis Room",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--2-21",
    dataSpace: "2.21",
    arialabel: "Pin for Stacey Sheriff",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-22",
    dataSpace: "2.22",
    arialabel: "Pin for Carol Hurney",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-23",
    dataSpace: "2.23",
    arialabel: "Pin for Jason Parkhill",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-24",
    dataSpace: "2.24",
    arialabel: "Pin for Karen Gillum",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-25",
    dataSpace: "2.25",
    arialabel: "Pin for Bonnie Paige",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-26",
    dataSpace: "2.26",
    arialabel: "Pin for Marilyn Pukkila",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-27",
    dataSpace: "2.27",
    arialabel: "Pin for Laine Thielstrom",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--2-28",
    dataSpace: "2.28",
    arialabel: "Pin for Stephanie Frost",
    svgClassName: "icon icon--logo icon--wrench",
    xlinkHref: "#icon-wrench",
    dataCategory: "1",
  },
  // Add more entries as needed
];

export const FifthFloorPins = [
  {
    aClass: "pin pin--5-1" as string,
    dataSpace: "5.01" as string,
    arialabel: "Pin for Darylyne Provost" as string,
    svgClassName: "icon icon--logo icon--appleheart" as string,
    xlinkHref: "#icon-appleheart" as string,
    dataCategory: "1" as string,
  },
  {
    aClass: "pin pin--5-2",
    dataSpace: "5.02",
    arialabel: "Pin for Mike McGuire",
    svgClassName: "icon icon--logo icon--bananas",
    xlinkHref: "#icon-bananas",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-3",
    dataSpace: "5.03",
    arialabel: "Pin for Matt LeVan",
    svgClassName: "icon icon--logo icon--origami",
    xlinkHref: "#icon-origami",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-4",
    dataSpace: "5.04",
    arialabel: "Pin for Mike Jandreau",
    svgClassName: "icon icon--logo icon--dress",
    xlinkHref: "#icon-dress",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-5",
    dataSpace: "5.05",
    arialabel: "Pin for Martin Kelly",
    svgClassName: "icon icon--logo icon--tree2",
    xlinkHref: "#icon-tree2",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-6",
    dataSpace: "5.06",
    arialabel: "Pin for Eileen Richards",
    svgClassName: "icon icon--logo icon--avocado",
    xlinkHref: "#icon-avocado",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-7",
    dataSpace: "5.07",
    arialabel: "Pin for Ground Level Stacks",
    svgClassName: "icon icon--logo icon--books",
    xlinkHref: "#icon-books",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--5-8",
    dataSpace: "5.08",
    arialabel: "Pin for Classroom 014",
    svgClassName: "icon icon--logo icon--pear",
    xlinkHref: "#icon-pear",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--5-9",
    dataSpace: "5.09",
    arialabel: "Pin for Mule Works Lab",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--5-10",
    dataSpace: "5.10",
    arialabel: "Pin for Special Collections Processing",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--5-11",
    dataSpace: "5.11",
    arialabel: "Pin for Classroom 008",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--5-12",
    dataSpace: "5.12",
    arialabel: "Pin for Room 009",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-13",
    dataSpace: "5.13",
    arialabel: "Pin for Room 009A",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-14",
    dataSpace: "5.14",
    arialabel: "Pin for Room 005",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--5-15",
    dataSpace: "5.15",
    arialabel: "Pin for Ana Noriega",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-16",
    dataSpace: "5.16",
    arialabel: "Pin for Katie Donahue",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-17",
    dataSpace: "5.17",
    arialabel: "Pin for Room 004",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-18",
    dataSpace: "5.18",
    arialabel: "Pin for Bess Stokes",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-19",
    dataSpace: "5.19",
    arialabel: "Pin for Study Rooms 020A-D",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--5-20",
    dataSpace: "5.20",
    arialabel: "Pin for Microfilm",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--5-21",
    dataSpace: "5.21",
    arialabel: "Pin for Hall Study Area",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--5-22",
    dataSpace: "5.22",
    arialabel: "Pin for Seminar Room",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-23",
    dataSpace: "5.23",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-24",
    dataSpace: "5.24",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-25",
    dataSpace: "5.25",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-26",
    dataSpace: "5.26",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--5-27",
    dataSpace: "5.27",
    arialabel: "Pin for ROOOOOOM",
    svgClassName: "icon icon--logo icon--rocket",
    xlinkHref: "#icon-rocket",
    dataCategory: "1",
  },

  // Add more entries as needed
];

export const ThirdFloorPins = [
  {
    aClass: "pin pin--3-1",
    dataSpace: "3.01",
    arialabel: "Pin for Second Floor Stacks",
    svgClassName: "icon icon--logo icon--books",
    xlinkHref: "#icon-books",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--3-2",
    dataSpace: "3.02",
    arialabel: "Pin for Second Floor Study Area",
    svgClassName: "icon icon--logo icon--pyramid",
    xlinkHref: "#icon-pyramid",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--3-3",
    dataSpace: "3.03",
    arialabel: "Pin for Farnham Writing Center",
    svgClassName: "icon icon--logo icon--grass",
    xlinkHref: "#icon-grass",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--3-4",
    dataSpace: "3.04",
    arialabel: "Pin for Room 205",
    svgClassName: "icon icon--logo icon--shirt",
    xlinkHref: "#icon-shirt",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--3-5",
    dataSpace: "3.05",
    arialabel: "Pin for Room 208",
    svgClassName: "icon icon--logo icon--shoe",
    xlinkHref: "#icon-shoe",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--3-6",
    dataSpace: "3.06",
    arialabel: "Pin for Meghan Hancock",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-7",
    dataSpace: "3.07",
    arialabel: "Pin for Ghada Gherwash",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-8",
    dataSpace: "3.08",
    arialabel: "Pin for Jordan Bailey",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-9",
    dataSpace: "3.09",
    arialabel: "Pin for Kerrill O'Neil",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-10",
    dataSpace: "3.10",
    arialabel: "Pin for Megan Fossa",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-11",
    dataSpace: "3.11",
    arialabel: "Pin for Paula Harrington",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-12",
    dataSpace: "3.12",
    arialabel: "Pin for FWC Tutor Office",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  {
    aClass: "pin pin--3-13",
    dataSpace: "3.13",
    arialabel: "Pin for Carolyn Megan",
    svgClassName: "icon icon--logo icon--tree",
    xlinkHref: "#icon-tree",
    dataCategory: "1",
  },
  // Add more entries as needed
];

export const FourthFloorPins = [
  {
    aClass: "pin pin--4-1",
    dataSpace: "4.01",
    arialabel: "Pin for Third Floor Stacks",
    svgClassName: "icon icon--logo icon--books",
    xlinkHref: "#icon-books",
    dataCategory: "4",
  },
  {
    aClass: "pin pin--4-2",
    dataSpace: "4.02",
    arialabel: "Pin for Third Floor Study Area",
    svgClassName: "icon icon--logo icon--pyramid",
    xlinkHref: "#icon-pyramid",
    dataCategory: "3",
  },
  {
    aClass: "pin pin--4-5",
    dataSpace: "4.06",
    arialabel: "Pin for Room 306 B",
    svgClassName: "icon icon--logo icon--tomato",
    xlinkHref: "#icon-tomato",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--4-8",
    dataSpace: "4.07",
    arialabel: "Pin for Room 306 C",
    svgClassName: "icon icon--logo icon--cinema",
    xlinkHref: "#icon-cinema",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--4-3",
    dataSpace: "4.05",
    arialabel: "Pin for Room 306 A",
    svgClassName: "icon icon--logo icon--paint-brush",
    xlinkHref: "#icon-paint-brush",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--4-4",
    dataSpace: "4.03",
    arialabel: "Pin for Room 305 B",
    svgClassName: "icon icon--logo icon--modx",
    xlinkHref: "#icon-modx",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--4-6",
    dataSpace: "4.04",
    arialabel: "Pin for Room 305 A",
    svgClassName: "icon icon--logo icon--cupcake",
    xlinkHref: "#icon-cupcake",
    dataCategory: "2",
  },
  {
    aClass: "pin pin--4-7",
    dataSpace: "4.08",
    arialabel: "Pin for Room 319",
    svgClassName: "icon icon--logo icon--leafcircle",
    xlinkHref: "#icon-leafcircle",
    dataCategory: "2",
  },
  // Add more entries as needed
];
